const allUsers = [
  {
  id: '1',
  name: 'robb',
  nickname: 'robb',
  email: 'robb@bento.com',
  passwordHash: 'xxxx',
  active: true,
  admin: 3,
  language: 'EN',
  defaultOrder: 'reverse_date',
  flat: false,
  hideDone: false,
  lastList: 102,
  },
  {
  id: '2',
  name: 'robby',
  nickname: 'robby',
  email: 'robbs@bento.com',
  passwordHash: 'xxxx',
  active: true,
  admin: 1,
  language: 'EN',
  defaultOrder: 'alpha',
  flat: false,
  hideDone: true,
  lastList: 103,
  }
];

const allCategories = [
  {
  id: '1',
  userID: '1',
  categoryName: 'to do',
  sortOrder: 2,
  creationDate: 0,
  lastUse: 0,
  active: true,
},
{
  id: '2',
  userID: '1',
  categoryName: 'shopping',
  sortOrder: 1,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '3',
  userID: '2',
  categoryName: 'stuff to do',
  sortOrder: 2,
  creationDate: 0,
  lastUse: 0,
  active: true,
},
{
  id: '4',
  userID: '2',
  categoryName: 'major shopping',
  sortOrder: 1,
  created: 0,
  lastUsed: 0,
  active: true,
},
];

const allLists = [
{
  id: '101',
  categoryID: '1',
  sortOrder: 2,
  userID: '1',
  listName: 'main to-do',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '102',
  categoryID: '2',
  sortOrder: 1,
  userID: '1',
  listName: 'main shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '103',
  categoryID: '3',
  sortOrder: 3,
  userID: '2',
  listName: 'main to-do',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '104',
  categoryID: '4',
  sortOrder: 4,
  userID: '2',
  listName: 'main shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
];

const allItems = [
{ 
  id: '10001',
  sortOrder: 2,
  listID: '101',
  userID: '1',
  itemName: 'start to-do list',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10002',
  sortOrder: 1,
  listID: '101',
  userID: '1',
  itemName: 'go bowling',
  itemNote: 'bring bowling shoes',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10003',
  sortOrder: 1,
  listID: '102',
  userID: '1',
  itemName: 'salt',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10004',
  sortOrder: 2,
  listID: '102',
  userID: '1',
  itemName: 'pepper',
  itemNote: 'with its own grinder',
  importance: 1,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10005',
  sortOrder: 1,
  listID: '103',
  userID: '2',
  itemName: 'water plants',
  itemNote: 'not the plastic ones though',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10006',
  sortOrder: 2,
  listID: '103',
  userID: '2',
  itemName: 'work on UI for list app',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10007',
  sortOrder: 1,
  listID: '104',
  userID: '2',
  itemName: 'olive oil',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10008',
  sortOrder: 2,
  listID: '104',
  userID: '2',
  itemName: 'balsamic vinegar',
  itemNote: '',
  importance: 1,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10009',
  sortOrder: 3,
  listID: '102',
  userID: '1',
  itemName: 'tomato sauce',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10010',
  sortOrder: 4,
  listID: '102',
  userID: '1',
  itemName: 'zucchinis',
  itemNote: 'green',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10011',
  sortOrder: 6,
  listID: '102',
  userID: '1',
  itemName: 'eggplants',
  itemNote: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  id: '10012',
  sortOrder: 5,
  listID: '102',
  userID: '1',
  itemName: 'aubergines',
  itemNote: 'like British eggplants',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},

];


export {allUsers, allCategories, allLists, allItems};  
