const allUsers = [
  {
  id: '1',
  name: 'robb',
  nickname: 'robb',
  email: 'robb@bento.com',
  passwordHash: 'xxxx',
  active: true,
  admin: 3,
  language: 'EN',
  defaultOrder: 'reverse_date',
  flat: false,
  hideDone: false,
  lastList: 102,
  },
  {
  id: '2',
  name: 'robby',
  nickname: 'robby',
  email: 'robbs@bento.com',
  passwordHash: 'xxxx',
  active: true,
  admin: 1,
  language: 'EN',
  defaultOrder: 'alpha',
  flat: false,
  hideDone: true,
  lastList: 103,
  }
];

const allCategories = [
  {
  id: '1',
  userid: '1',
  categoryName: 'to do',
  categoryPos: 1,
  creationDate: 0,
  lastUse: 0,
  active: true,
},
{
  id: '2',
  userid: '1',
  categoryName: 'shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '3',
  userid: '2',
  categoryName: 'stuff to do',
  categoryPos: 1,
  creationDate: 0,
  lastUse: 0,
  active: true,
},
{
  id: '4',
  userid: '2',
  categoryName: 'major shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
];

const allLists = [
{
  id: '101',
  categoryid: '1',
  listpos: 0,
  userid: '1',
  listName: 'main to-do',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '102',
  categoryid: '2',
  listpos: 0,
  userid: '1',
  listName: 'main shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '103',
  categoryid: '3',
  listpos: 0,
  userid: '2',
  listName: 'main to-do',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
{  
  id: '104',
  categoryid: '4',
  listpos: 0,
  userid: '2',
  listName: 'main shopping',
  categoryPos: 0,
  created: 0,
  lastUsed: 0,
  active: true,
},
];

const allItems = [
{ 
  itemid: '10001',
  itempos: 0,
  listid: '101',
  userid: '1',
  itemname: 'start to-do list',
  itemnotes: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10002',
  itempos: 1,
  listid: '101',
  userid: '1',
  itemname: 'go bowling',
  itemnotes: 'bring bowling shoes',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10003',
  itempos: 0,
  listid: '102',
  userid: '1',
  itemname: 'salt',
  itemnotes: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10004',
  itempos: 1,
  listid: '102',
  userid: '1',
  itemname: 'pepper',
  itemnotes: 'with its own grinder',
  importance: 1,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10005',
  itempos: 0,
  listid: '103',
  userid: '2',
  itemname: 'water plants',
  itemnotes: 'not the plastic ones though',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10006',
  itempos: 1,
  listid: '103',
  userid: '2',
  itemname: 'work on UI for list app',
  itemnotes: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10007',
  itempos: 0,
  listid: '104',
  userid: '2',
  itemname: 'olive oil',
  itemnotes: '',
  importance: 0,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
{   
  itemid: '10008',
  itempos: 1,
  listid: '104',
  userid: '2',
  itemname: 'balsamic vinegar',
  itemnotes: '',
  importance: 1,
  created: 0,
  lastUsed: 0,
  active: true,
  done: false,
},
];


export {allUsers, allCategories, allLists, allItems};  
